# Generated by Django 5.2.8 on 2026-02-21 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcard',
            options={'verbose_name': 'بطاقة طالب', 'verbose_name_plural': 'بطاقات الطلاب'},
        ),
        migrations.AlterField(
            model_name='studentcard',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='studentcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='studentcard',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='studentcard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_card', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
