# Generated by Django 5.2.8 on 2026-02-21 21:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookauthor',
            options={'verbose_name': 'مؤلف', 'verbose_name_plural': 'المؤلفون'},
        ),
        migrations.AlterModelOptions(
            name='bookfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'تقييم', 'verbose_name_plural': 'التقييمات'},
        ),
        migrations.AlterModelOptions(
            name='borrowticket',
            options={'ordering': ['-borrowed_at'], 'verbose_name': 'استعارة', 'verbose_name_plural': 'الاستعارات'},
        ),
        migrations.AlterModelOptions(
            name='contactinbox',
            options={'ordering': ['-created_at'], 'verbose_name': 'رسالة تواصل', 'verbose_name_plural': 'رسائل التواصل'},
        ),
        migrations.AlterModelOptions(
            name='librarybook',
            options={'ordering': ['-added_at'], 'verbose_name': 'كتاب', 'verbose_name_plural': 'الكتب'},
        ),
        migrations.AlterModelOptions(
            name='pagevisit',
            options={'ordering': ['-created_at'], 'verbose_name': 'زيارة', 'verbose_name_plural': 'سجل الزيارات'},
        ),
        migrations.AlterModelOptions(
            name='shelfcategory',
            options={'verbose_name': 'تصنيف', 'verbose_name_plural': 'التصنيفات'},
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='bio',
            field=models.TextField(blank=True, verbose_name='نبذة'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='display_name',
            field=models.CharField(max_length=170, verbose_name='اسم المؤلف'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='صورة المؤلف'),
        ),
        migrations.AlterField(
            model_name='bookfeedback',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='libraryapp.librarybook', verbose_name='الكتاب'),
        ),
        migrations.AlterField(
            model_name='bookfeedback',
            name='comment',
            field=models.TextField(blank=True, verbose_name='التعليق'),
        ),
        migrations.AlterField(
            model_name='bookfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم'),
        ),
        migrations.AlterField(
            model_name='bookfeedback',
            name='stars',
            field=models.PositiveIntegerField(default=5, verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='bookfeedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='borrowticket',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='libraryapp.librarybook', verbose_name='الكتاب'),
        ),
        migrations.AlterField(
            model_name='borrowticket',
            name='borrowed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاستعارة'),
        ),
        migrations.AlterField(
            model_name='borrowticket',
            name='due_at',
            field=models.DateTimeField(verbose_name='تاريخ الإرجاع المتوقع'),
        ),
        migrations.AlterField(
            model_name='borrowticket',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرجاع'),
        ),
        migrations.AlterField(
            model_name='borrowticket',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='contactinbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال'),
        ),
        migrations.AlterField(
            model_name='contactinbox',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='contactinbox',
            name='full_name',
            field=models.CharField(max_length=120, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='contactinbox',
            name='message',
            field=models.TextField(verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='contactinbox',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='الموضوع'),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='libraryapp.bookauthor', verbose_name='المؤلف'),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='libraryapp.shelfcategory', verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='صورة الغلاف'),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('AR', 'Arabic'), ('FR', 'French'), ('OT', 'Other')], default='EN', max_length=2, verbose_name='اللغة'),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='pages_total',
            field=models.PositiveIntegerField(default=120, verbose_name='عدد الصفحات'),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='published_year',
            field=models.PositiveIntegerField(default=2020, verbose_name='سنة النشر'),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='title',
            field=models.CharField(max_length=240, verbose_name='عنوان الكتاب'),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='total_copies',
            field=models.PositiveIntegerField(default=1, verbose_name='إجمالي النسخ'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت الزيارة'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='ip',
            field=models.CharField(blank=True, max_length=60, verbose_name='عنوان IP'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='path',
            field=models.CharField(max_length=400, verbose_name='المسار'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='shelfcategory',
            name='icon_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='الأيقونة'),
        ),
        migrations.AlterField(
            model_name='shelfcategory',
            name='label',
            field=models.CharField(max_length=120, unique=True, verbose_name='اسم التصنيف'),
        ),
    ]
